### ISSUE TITLE
When release the code of IHMR？

### ISSUE THREAD

**Issue by CASlzwde** [jiawei-ren/BalancedMSE#1]

**Comment by jiawei-ren** [comment]
We are preparing the code, it should be released soon.

**Comment by CASlzwde** [comment]
Thanks for your reply. And I'm waiting for the code to release

**Comment by jiawei-ren** [comment]
The code for IHMR has been released in [mmHuman3D](https://github.com/open-mmlab/mmhuman3d). Config, pretrained models, and logs are [here](https://github.com/open-mmlab/mmhuman3d/tree/main/configs/balanced_mse).
