### ISSUE TITLE
Bad performance on train set

### ISSUE THREAD

**Issue by Witiy** [jiawei-ren/BalancedMSE#12]
Hi. I apply bMSE on my task which is a single-dimensional regression task. I found that the performance on train set is weird. The prediction of relatively low value data point is very high. In all, the performance on train set is bad. So it is normal? Looking forward to your reply!

**Comment by jiawei-ren** [comment]
It is normal that there is a performance drop on the train set when measured in _standard metrics_ like MSE, MAE, and RMSE. Balanced MSE is expected to bring a performance gain when measured in _balanced metrics_. 

For balanced metrics, you may uniformly divide the label space into ranges and average the error on the ranges. Alternatively, you may use a balanced validation set to evaluate the performance.
