### ISSUE TITLE
The formula derivation is a little unclear.

### ISSUE THREAD

**Issue by plplpl22223** [jiawei-ren/BalancedMSE#13]
**A.6 to A.7 can't understand how to convert, could you explain in more detail, thank you.**
![image](https://user-images.githubusercontent.com/102735179/171123343-3db547ef-8abb-45fc-8635-c9868507150c.png)

**Comment by jiawei-ren** [comment]
Since the balanced label distribution is uniform, $p_{bal}(y) = c$ for all $y$. Therefore, in A.6, $p_{bal}(y)$ in the numerator and $p_{bal}(y^\prime)$ in the denominator canceled out. We hence obtain A.7.

**Comment by plplpl22223** [comment]
> 

ok i think i get it, thanks a lot for your reply.
