### ISSUE TITLE
Dose BMCloss only work for minibatch > 1? 

### ISSUE THREAD

**Issue by ccxsun** [jiawei-ren/BalancedMSE#14]
The bmcloss equals 0.0 when I added BMCloss to my project with minibatch==1. 
I noticed that bmcloss is calculated by treating the regression predictions in a batch as multiclass classification. But since the size of each of my samples is different, my minibatch can only be set to 1.
Is it not feasible to apply bmcloss in this case?

**Comment by jiawei-ren** [comment]
Yes. In this case, other loss variations like GAI will be more suitable. GAI precomputes the label statistics.

**Comment by ccxsun** [comment]
Thanks for your reply!
