### ISSUE TITLE
In my task, Balance MSE loss decreases but MES loss increases.

### ISSUE THREAD

**Issue by shoutOutYangJie** [jiawei-ren/BalancedMSE#15]
It seem to not suitable for my task.

**Comment by shoutOutYangJie** [comment]
what function does "init_noise_sigma" have?
I find when I set "init_noise_sigma" as 0.01. The mse loss was decreasing.

**Comment by shoutOutYangJie** [comment]
Now，L2 loss starts to increase.
![image](https://user-images.githubusercontent.com/46734514/174561953-4ea97e4b-23be-44eb-b1a1-91a2b3d13317.png)

**Comment by jiawei-ren** [comment]
It is expected that L2 loss will increase at some point. L2 and Balanced MSE have different optimization objectives.

**Comment by shoutOutYangJie** [comment]
> 

Finally, I find balance MSE is not suitable  to my task.

**Comment by shoutOutYangJie** [comment]
In my task , I have totaly 60 dims to regress.
