### ISSUE TITLE
reconstruction loss

### ISSUE THREAD

**Issue by HanAccount** [jiawei-ren/BalancedMSE#6]
Hi!
Can it be applied to image reconstruction loss?
because image reconstruction loss is often used in MSE

**Comment by jiawei-ren** [comment]
I don't think so if you are using metrics like FID. 

Balanced MSE tackles the mismatch between imbalanced training data and balanced test data/evaluation metrics. However, image reconstruction metrics often encourage an exact match between the training data and the generated data.

**Comment by HanAccount** [comment]
Right! thanks
