### ISSUE TITLE
Are there some tricks to use BalancedMse in MultiDimension data？

### ISSUE THREAD

**Issue by Feywell** [jiawei-ren/BalancedMSE#7]
I try to use BalacedMSE in a multidimension data regrssion task.
But it is not work. Althought, the loss is smaller and smaller, the result is bad.

**Comment by jiawei-ren** [comment]
Please provide a more detailed issue description, e.g., what task are you working on.

**Comment by FouriYe** [comment]
I also adopted BMC in a multi-label regression. But the results seem far worse than standard MSE.
May I ignore some details. I'm trying to understand the code.

**Comment by jiawei-ren** [comment]
Please make sure that you are using a balanced test set or evaluation metric. Meanwhile, more details would be appreciated.

**Comment by lijain** [comment]
> I try to use BalacedMSE in a multidimension data regrssion task. But it is not work. Althought, the loss is smaller and smaller, the result is bad.

I also had the same problem, a multi-dimensional [n, 4] regression, a loss loss of 4 times the previous one and the result was not very good

**Comment by jiawei-ren** [comment]
> I also had the same problem, a multi-dimensional [n, 4] regression, a loss loss of 4 times the previous one and the result was not very good

Duplicate with https://github.com/jiawei-ren/BalancedMSE/issues/10.
