### ISSUE TITLE
err

### ISSUE THREAD

**Issue by sssssshf** [jiawei-ren/BalancedMSE#8]
def bmc_loss_md(pred, target, noise_var):
    I = torch.eye(pred.shape[-1]).cuda()
    logits = MVN(pred.unsqueeze(1), noise_var*I)
    logits = logits.log_prob(target.unsqueeze(0))
    loss = F.cross_entropy(logits, torch.arange(pred.shape[0]))
    loss = loss * (2 * noise_var).detach()
    return loss
用于ssrnet年龄回归任务。
在这一段代码中，loss = F.cross_entropy(logits, torch.arange(pred.shape[0]))　报错：
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)　

回归任务不就是一维的吗。

**Comment by sssssshf** [comment]
logits = - (pred - target.T).pow(2) / (2 * noise_var)   # logit size: [batch, batch]
这里输出的logits size为一维[128] 不是[128,128]

**Comment by jiawei-ren** [comment]
Please make sure that both `pred` and `target` have the size [batch, 1]. You may try `pred = pred.unsqueeze(-1)` and `target = target.unsqueeze(-1)`.

**Comment by sssssshf** [comment]
> 请确保两者都`pred`具有`target`大小 [batch, 1]。你可以试试`pred = pred.unsqueeze(-1)`和`target = target.unsqueeze(-1)`。

可以了　多谢大帅比
